version: '3.8'

services:
  db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: task_scheduler
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: Somoprovo.01
    ports:
      - "4201:4201"
    volumes:
      - mysql_data:/var/lib/mysql

  app:
    build: .
    depends_on:
      - db
    environment:
      SQLALCHEMY_DATABASE_URL: mysql+pymysql://root:Somoprovo.01@localhost:4201/task_scheduler
    ports:
      - "8000:8000"

volumes:
  mysql_data:
