apiVersion: batch/v1
kind: Job
metadata:
  name: task-job
spec:
  template:
    spec:
      containers:
      - name: task-container
        image: task-scheduler  # Replace with the name of your Docker image
        command: ["python", "./main.py"]
      restartPolicy: Never
  backoffLimit: 1
